#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#


"""

Programa para coleta de notícias do site BBC Brasil

Usage:
    get-info bbc
    get-info folha
    get-info transparencia <cpf>
    get-info irpf <cpf> <dn>
    get-info wa
    get-info bdfato
    get-info correioweb
    get-info sae <matricula> <periodo>


Options:
    --version

"""

import os

from docopt import docopt

from modules.web_scraping_base import get_bbc_news, bbc_br, get_folha_news, procurar_no_portal_da_transparencia, pop_up_consulta_irpf, send_via_whatsappweb, get_br_de_fato_news, pop_up_novo_sae_estudo_info, get_correioweb_news
from modules.news_pastas_de_dados import pasta_dados

args = docopt(__doc__)

def minimal_info_check():
    pass

def main():
    minimal_info_check()
    if args['bbc']:
        newid = os.fork()
        if newid == 0:
            print('Buscando informações em BBC Brasil...')
            get_bbc_news(target_folder=pasta_dados)
    
    elif args['folha']:
        get_folha_news(target_folder=pasta_dados)

    elif args['transparencia']:
        procurar_no_portal_da_transparencia(args['<cpf>'])

    elif args['irpf']:
        pop_up_consulta_irpf(args['<cpf>'], args['<dn>'])

    elif args['wa']:
        send_via_whatsappweb()

    elif args['bdfato']:
        newid = os.fork()
        if newid == 0:
            print('Buscando informações em Brasil de Fato...')
            get_br_de_fato_news(target_folder=pasta_dados)

    elif args['correioweb']:
        newid = os.fork()
        if newid == 0:
            print('Buscando informações em Correio Web...')
            get_correioweb_news(target_folder=pasta_dados)


    elif args['sae']:
        pop_up_novo_sae_estudo_info(args['<matricula>'], args['<periodo>'])


if __name__ == '__main__':
	main()
